### ISSUE TITLE
Error Connecting

### ISSUE THREAD

**Issue by mmaruri** [hannonhill/Webservices-PHP-Sample-Project#5]
When I try and connect to the AssetOperationService I get a Soap Error.  Couldn't find <definitions>.  Any ideas?

**Comment by mmaruri** [comment]
"SOAP-ERROR: Parsing WSDL: Couldn't find definitions in '/AssetOperationService?wsdl'"

I removed most of the path for this post.

**Comment by bradical** [comment]
I'm guessing your webservices endpoint: `http://<YOUR_CASCADE_URL>/ws/AssetOperationService?wsdl` is not publicly accessible from the place you're running your script. Please file something here: http://help.hannonhill.com/discussions/web-services and we can help troubleshoot.
